main: com.cavetale.fam.FamPlugin

name: Fam
version: 0.1
description: Fam Plugin
api-version: 1.13

author: StarTux
website: https://github.com/StarTux/Fam

depend: [SQL, Mytems, PlayerCache, Sidebar]
softdepend: []

commands:

  fam:
    aliases: []
    description: Admin command
    permission: fam.fam
    usage: |-
      /fam info

  friends:
    aliases: []
    description: Friend list
    permission: fam.friends
    usage: /friends [name]

  valentine:
    aliases: []
    description: Valentine Rewards
    permission: fam.friends
    usage: |-
      §e/valentine§8 - §fOpen rewards menu
      §e/valentine hi§8 - §fView highscore

  friend:
    aliases: []
    description: Friend request
    permission: fam.friends
    usage: /friend <player>

  love:
    aliases: []
    description: Send love to your spouse
    permission: fam.marriage
    usage: /love

permissions:

  fam.fam:
    description: Use /fam
    default: op

  fam.friends:
    description: Make friends and use /friends
    default: op

  fam.marriage:
    description: Get married
    default: false