main: com.cavetale.fam.FamPlugin

name: Fam
version: 0.1
description: Fam Plugin
api-version: 1.18

author: StarTux
website: https://github.com/StarTux/Fam

depend: [Core, SQL, Mytems, PlayerCache, Sidebar, Connect]
softdepend: []

commands:

  fam:
    aliases: []
    description: Admin command
    permission: fam.admin
    usage: |-
      /fam info - Dump debug info
      /fam compute - Compute possible daybreak
      /fam daybreak - Simulate daybreak
      /fam config - Save default config

  profile:
    aliases: []
    description: View profile page
    permission: fam.friends
    usage: /profile

  friends:
    aliases: []
    description: Friendship list
    permission: fam.friends
    usage: /friends [name]

  valentine:
    aliases: []
    description: Valentine Rewards
    permission: fam.valentine
    usage: |-
      /valentine - Open rewards menu
      /valentine hi - View highscore

  friend:
    aliases: []
    description: Friend request
    permission: fam.friends
    usage: /friend <player>

  love:
    aliases: []
    description: Send love to your partner
    permission: fam.marriage
    usage: /love

  divorce:
    aliases: []
    description: Divorce your partner
    permission: fam.marriage
    usage: /divorce

permissions:

  fam.admin:
    description: Use /fam
    default: op

  fam.friends:
    description: Make friends and use /friends
    default: op

  fam.marriage:
    description: Get married
    default: false

  fam.debug:
    description: View debug information
    default: op